<?php

namespace Database\Seeders;

use App\Models\Image;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Product::factory(60)->create()->each(function(Product $product){
        //     Image::factory(2)->create([
        //         'imageable_id'=>$product->id,
        //         'imageable_type'=>Product::class
        //     ]);
        // });

        $products = [
            [
                'name' => 'Archivador de colores',
                'slug' => 'archivador-de-colores',
                'description' => 'Archivador de colores',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Borrador',
                'slug' => 'borrador',
                'description' => 'Borrador',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Calculadora',
                'slug' => 'calculadora',
                'description' => 'Calculadora',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Chinches indicadores',
                'slug' => 'chinches-indicadores',
                'description' => 'Chinches indicadores',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cinta',
                'slug' => 'cinta',
                'description' => 'Cinta',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cinta de embalaje',
                'slug' => 'cinta-de-embalaje',
                'description' => 'Cinta de embalaje',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cola sintetica Pegafan',
                'slug' => 'cola-sintetica-pegafan',
                'description' => 'Cola sintetica Pegafan',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cola blanca',
                'slug' => 'cola-blanca',
                'description' => 'Cola blanca',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Colores',
                'slug' => 'colores',
                'description' => 'Colores',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Correctores',
                'slug' => 'correctores',
                'description' => 'Correctores',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cuadernos con diseño',
                'slug' => 'cuadernos-con-diseño',
                'description' => 'Cuadernos con diseño',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Cuadernos solidos',
                'slug' => 'cuadernso-solidos',
                'description' => 'Cuadernos solidos',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Dispensador de cinta',
                'slug' => 'dispensador-de-cinta',
                'description' => 'Dispensador de cinta',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Engrapador Artesco',
                'slug' => 'engrapador-artesco',
                'description' => 'Engrapador Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Escuadra Artesco',
                'slug' => 'escuadra-artesco',
                'description' => 'Escuadra Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Forro Artesco',
                'slug' => 'forro-artesco',
                'description' => 'Forro Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Forro Vinifan',
                'slug' => 'forro-vinifan',
                'description' => 'Forro Vinifan',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Fundas potapapel',
                'slug' => 'fundas-portapapel',
                'description' => 'Fundas portapapel',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Grapador',
                'slug' => 'grapador',
                'description' => 'Grapador',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Grapas Artesco',
                'slug' => 'grapas-artesco',
                'description' => 'Grapas Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Grapas Rapid',
                'slug' => 'grapas-rapid',
                'description' => 'Grapas Rapid',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Lapicero Pilot',
                'slug' => 'lapicero-pilot',
                'description' => 'Lapicero Pilot',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Lapiceros Trilux',
                'slug' => 'lapiceros-trilux',
                'description' => 'Lapicero Trilux',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Lapiz grafito',
                'slug' => 'lapiz-grafito',
                'description' => 'Lapiz grafito',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Marcador fluorescente amarillo',
                'slug' => 'marcador-fluorescente-amarillo',
                'description' => 'Marcador fluorescente amarillo',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Notitas',
                'slug' => 'notitas',
                'description' => 'Notitas',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Pegamento en barra',
                'slug' => 'pegamento-en-barra',
                'description' => 'Pegamento en barra',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Perforador Faber',
                'slug' => 'perforador-faber',
                'description' => 'Perforador Faber',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Perforador Artesco',
                'slug' => 'perforador-artesco',
                'description' => 'Perforador Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Plumon grueso Faber',
                'slug' => 'plumon-grueso-faber',
                'description' => 'Plumon Grueso Faber',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Plumon de pizarra outline',
                'slug' => 'plumon-de-pizarra-outline',
                'description' => 'Plumon de pizarra outline',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Plumon de pizarra',
                'slug' => 'plumon-pizarra',
                'description' => 'Plumon de pizarra',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Porta utiles',
                'slug' => 'porta-utiles',
                'description' => 'Porta utiles',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Resaltadores',
                'slug' => 'resaltadores',
                'description' => 'Resaltadores',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Saca grapas',
                'slug' => 'saca-grapas',
                'description' => 'Saca grapas',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Silicona Artesco',
                'slug' => 'silicona-artesco',
                'description' => 'Silicona Artesco',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Silicona Arti',
                'slug' => 'silicona-arti',
                'description' => 'Silicona Arti',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Silicona Faber',
                'slug' => 'silicona-faber',
                'description' => 'Silicona Faber',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => '',
                'slug' => '',
                'description' => '',
                'subcategory_id' => 1,
                'price' => 9.99,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Silicona Ove',
                'slug' => 'silicona-ove',
                'description' => 'Silicona Ove',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Silicona Vinifan',
                'slug' => 'silicona-vinifan',
                'description' => 'Silicona Vinifan',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
            [
                'name' => 'Tijeras',
                'slug' => 'tijeras',
                'description' => 'Tijeras',
                'price' => 9.99,
                'subcategory_id' => 1,
                'quantity' => 15,
                'status' => 2,
            ],
        ];

        foreach($products as $product) {
            $product = Product::factory(1)->create($product)->first();
        }

    }
}
